apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  includeCRDs: true
  namespace: external-secrets
  version: 0.6.0-rc1
  valuesFile: values.yaml
