apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-workflows
  repo: https://charts.akuity.io
  includeCRDs: true
  namespace: argo-workflows
  version: 1.2.1
  valuesFile: values.yaml

resources:
- podmonitor.yaml

patchesStrategicMerge:
- deployment-patch.yaml
