apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::541216676946:role/argo-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::541216676946:role/argo-server-demo
