apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prod
  name: argo-wf-monitor
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: workflow-controller
