
server:
  secure: true
  service:
    type: LoadBalancer
  ingress:
    enabled: false

config:
  workflowDefaults: |
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 8848
      activeDeadlineSeconds: 7200
      ttlStrategy:
        secondsAfterSuccess: 600
        secondsAfterFailure: 3600
      podGC:
        strategy: OnWorkflowSuccess
      parallelism: 16
