apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-issuer
spec:
  acme:
    email: nikita@akuity.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-issuer-account-key
    solvers:
    - dns01:
        cloudDNS:
          project: akuity-academy
