installCRDs: true
securityContext:
  fsGroup: 1001
global:
  leaderElection:
    namespace: cert-manager
prometheus:
  enabled: false
serviceAccount:
  create: true
  name: cert-manager
  annotations:
    iam.gke.io/gcp-service-account: cert-manager@akuity-academy.iam.gserviceaccount.com
