apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true
  releaseName: prod
  namespace: prometheus
  version: 41.3.2
  valuesFile: values.yaml

patchesStrategicMerge:
  - toolong-patch.yaml
