grafana:
  enabled: false
defaultRules:
  create: false
kubeControllerManager:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheusOperator:
  kubeletService:
    enabled: false
